apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: buysbox
  name: buysbox
spec:
  containers:
  - image: busybox:latest
    name: buysbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
