baseurl = "https://www.malipraveen.net/"
title = "Miles to go 1.0"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "@praveenmali"

[params]
    author = "Praveen Mali"
    description = "Praveen Mali's website and blogging platform"
    keywords = "blog,developer,personal,devops,"
    info = "DevOps and Kubernetes Guy"
    avatarurl = "images/pic/avatar.jpg"
    footercontent = "Maintained by Praveen Mali"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/prvnmali2017"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 2
    url = "https://www.instagram.com/prvnmali"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/prvnmali"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/prvnmali/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@praveenmali"
[[params.social]]
    name = "Strava"
    icon = "fab fa-strava"
    weight = 6
    url = "https://www.strava.com/athletes/31749139"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Recent Posts"
        weight = 2
        url = "/posts/"
 
        [[languages.en.menu.main]]
        name = "Recent Posts"
        weight = 3
        url = "/serverless/"       

        [[languages.en.menu.main]]
        name = "Talks & Presentations"
        weight = 4
        url = "/Talks/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"

        [[languages.en.menu.main]]
        name = "Resume"
        weight = 6
        url = "/resume/"

        [[languages.en.menu.main]]
        name = "Miscellany"
        weight = 7
        url = "/miscellany/"

#    [languages.pt-br]
        languagename = "Português"
        title = "João Ninguém"

        [languages.pt-br.params]
            author = "João Ninguém"
            info = "Full Stack DevOps e Mágico"
            description = "Sítio pessoal de João Ninguém"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "Coloque algum texto aqui."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "/pt-br/about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "/pt-br/posts/"

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "/pt-br/projects/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "/pt-br/contact/"